#!/usr/bin/perl

# TODO  attacks
#       equipment (and if it can weaponattack)
#       what does it drop when dead
#       behaviors

use strict;
use warnings;
use Util;

# Since it's easier to compare this way visually
my @cols = (qw(Symbol Color Rank HP HP_Rate Def Dext Speed));
my @table = (
  #                                 1-10   1-15      1-5      1-15    1-10     1-5
  # Name           Symbol  Color    Rank    HP     HP_Rate     Def    Dext    Speed
  ["rat",           "r", "orange",   1,     1,       1,         1,     2,       1],
  ["cat",           "c", "orange",   1,     2,       2,         2,     3,       1],
  ["dog",           "d", "orange",   1,     2,       1,         2,     1,       1],
  ["tentacle",      "~",   "Cyan",   1,     1,       1,         2,     4,       3],
  ["codebug",       "b",  "green",   1,     3,       1,         3,     2,       1],

  ["mosquito",      "z",   "blue",   2,     3,       2,         2,     3,       3],
  ["steambubble",   "o",  "white",   2,     1,       1,         2,     4,       3],
  ["snake",         "S", "orange",   2,     3,       1,         3,     2,       2],

  ["joke",          "J",    "red",   3,     3,       2,         4,     3,       1],
  ["rooster",       "z", "orange",   3,     3,       1,         2,     3,       1],
  ["emoticon",      "P",    "red",   3,     5,       1,         4,     5,       1],
  ["worrywart",     "w",    "red",   3,     4,       1,         3,     4,       1],
  ["monkey",        "m", "orange",   3,     3,       2,         2,     7,       4],

  ["teddybear",     "B",   "blue",   4,     5,       2,         6,     2,       1],
  ["boar",          "b", "orange",   4,     4,       1,         5,     2,       2],
  ["rabbit",        "R", "orange",   4,     2,       1,         1,     6,       2],
  ["sheep",         "s", "orange",   4,     4,       1,         4,     1,       1],
  ["goat",          "G",    "red",   4,     3,       1,         4,     2,       1],
  ["serpent",       "S",  "white",   4,     5,       1,         5,     5,       2],
  ["drone",         "D",   "grey",   4,     6,       2,         6,     3,       2],
  ["clown",         "C", "yellow",   4,     5,       1,         5,     4,       2],

  ["Anonymous",     "A",  "white",   5,     6,       2,         5,     5,       1],
  ["tiger",         "t", "orange",   5,     5,       1,         5,     5,       2],
  ["ox",            "o", "orange",   5,     4,       1,         6,     3,       2],
  ["dromedary",     "D",   "grey",   5,     7,       1,         7,     2,       1],
  ["toysoldier",    "T",   "grey",   5,     6,       1,         6,     3,       1],
  ["roguegear",     "*", "orange",   5,     5,       1,         5,     7,       2],
  ["memory",        "M", "Purple",   5,     5,       1,         5,     7,       1],
  ["horse",         "H", "orange",   5,     7,       1,         8,     7,       2],
  ["wolf",          "W",  "white",   5,     5,       1,         6,     7,       2],

  ["turtle",        "T",  "green",   6,     8,       1,         9,     1,       1],
  ["spider",        "X",  "black",   6,     7,       3,         6,     7,       2],
  ["zeppelin",      "Z", "purple",   6,     5,       2,         5,     8,       3],
  ["clockbot",      "H",   "grey",   6,     6,       1,         7,     2,       1],
  ["BSOD",      "B", "black/Blue",   6,     7,       1,         6,     4,       1],

  ["octopus",       "O", "Purple",   7,     9,       2,         9,     1,       1],
  ["steamcloud",    "O",  "white",   7,     7,       2,         8,     8,       3],

  ["dragon",        "D", "orange",   8,    11,       3,        11,     2,       1],
  ["eyeball",       "E", "yellow",   8,     9,       1,         7,    12,       2],
  ["mandrake",      "M",  "green",   8,    12,       4,        12,     1,       1],

  ["friendzone",    "Z", "purple",   9,     9,       2,         9,     9,       1],
  ["snowgolem",     "G",   "Cyan",   9,    12,       1,        13,     2,       1],
  ["icestatue",     "{",   "grey",   9,    13,       1,        14,     1,       1],
  ["succubus",      "S",    "red",   9,     9,       4,        10,    10,       3],
  ["incubus",       "I",    "red",   9,     9,       4,        11,     9,       3],
  ["angel",         "A",   "Cyan",   9,    10,       3,         9,    10,       4],
  ["demon",         "D",    "Red",   9,    10,       4,        12,    11,       4],

  ["shadow",        "_",  "white",  10,    12,       3,         9,    14,       5],
  ["gumbybrain",    "G", "Purple",  10,    15,       4,        12,     9,       1],
  ["kraken",        "K", "Purple",  10,    15,       2,        15,    12,       2],
  ["oroborous",     "8",   "Cyan",  10,    15,       4,        15,    15,       5],
);
my %attacks = (
# Monster       Attack            Range   Lag  Damage     Effects
angel       => [],
Anonymous   => [["meme",           "adj",   2,   4,                                     ],
                ["summon",         "adj",   4,   0,  Summon     => [50, "codebug", 4]   ]],
boar        => [["tackle",         "adj",   1,   3,                                     ]],
BSOD        => [],
cat         => [["scratch",        "adj",   1,   1,                                     ]],
clockbot    => [],
clown       => [["blackhumor",     "adj",   4,   3,  Charm      => [10]                 ]],
codebug     => [["headache",       "adj",   3,   2,  Drain      => ["ESM", 1, 5]        ]],
demon       => [],
dog         => [["pesterpaw",      "adj",   1,   2,                                     ]],
dragon      => [["tail",     ["beam", 3],   2,   9,                                     ]],
dromedary   => [["saliva",  ["fire", 10],   2,   4,  Paralyze   => [5]                  ]],
drone       => [],
emoticon    => [["tongueslash",    "adj",   3,   2,                                     ],
                ["emote1",         "adj",   3,   0,  Inhibit    => ["HP", 10]           ],
                ["emote2",         "adj",   3,   0,  Infatuate  => [15]                 ]],
eyeball     => [],
friendzone  => [],
goat        => [["nomtarot",       "adj",   3,   0,  StealItem  => ["tarotcard", 75]    ],
                ["horncurse",      "adj",   2,   5,  CurseItem  => ["", "50%"]          ]],
gumbybrain  => [],
horse       => [["sacrifice",      "adj",   1,   6,  Suicide    => [80]                 ]],
icestatue   => [],
incubus     => [],
joke        => [["jawbreaker",["fire", 5],  4,   2,                                     ]],
kraken      => [],
mandrake    => [],
memory      => [],
monkey      => [["gomenasai",      "adj", 0.8, 0.5,                                     ]],
mosquito    => [["sting",          "adj",   3,   2,  Infatuate  => [8]                  ]],
octopus     => [["backup",         "adj",   5,   0,  Summon     => [60, "tentacle", 4]   ],
                ["inkjet",   ["fire", 7],   2,   5,                                     ]],
oroborous   => [],
ox          => [["black",          "adj",   5,   5,                                     ],
                ["white",          "adj",   3,   2,                                     ]],
rabbit      => [],
rat         => [["bite",           "adj",   1,   1,                                     ]],
roguegear   => [],
rooster     => [["scratch",        "adj",   1,   2,                                     ]],
serpent     => [],
shadow      => [],
sheep       => [["charge",         "adj",   6,   3,                                     ]],
snake       => [["lick",           "adj",   1,   2,                                     ],
                ["squeeze",        "adj",   3,   3,  Paralyze   => [3]                  ]],
snowgolem   => [],
spider      => [["venom",    ["fire", 7],   2,   7,  Drain      => ["HP", 2, 10]        ],
                ["entangle",       "adj",   3,   6,  Paralyze   => [5]                  ]],
steambubble => [["explode",        "adj",   1,   3,  Suicide    => [100]                ]],
steamcloud  => [],
succubus    => [],
teddybear   => [["hug",            "adj",   5,   2,                                     ],
                ["claw",           "adj",   4,   3,                                     ]],
tentacle    => [["squirt",   ["fire", 5],   2,   1,                                     ],
                ["grab",           "adj",   4,   1,  Paralyze   => [3]                  ]],
tiger       => [["wallflower",     "adj",   3,   4,                                     ]],
toysoldier  => [],
turtle      => [["shellbash",      "adj",   8,   5,                                     ]],
wolf        => [],
worrywart   => [["distract",       "adj",   2,   2,  Inhibit    => ["ESM", 10]          ],
                ["crownthorns",    "adj",   8,   4,                                     ]],
zeppelin    => [["sting",          "adj",   2,   6,                                     ],
                ["lawsuit",        "adj",   4,   5,  Charm      => [15]                 ]],
);

# For extra non-tabular data
my %dat = (
  rat => {
    Name   => "zodiac rat",
    Descr  => "The noble mouse grows a spine, hunched crooked in that dark closet ajar.",
    Pack   => 1
  },
  cat => {
    Name   => "zodiac cat",
    Descr  => "The cat was unable to attend the banquet due to fighting you.",
    # rage mode
  },
  dog => {
    Name   => "zodiac dog",
    Descr  => "The dog haunts high schools for all the wrong reasons."
    # follows but doesnt harm females
  },
  boar => {
    Name   => "zodiac boar",
    Descr  => "The pig squeals angrily one moment, nuzzling you the next.",
  },
  rabbit => {
    Name   => "zodiac rabbit",
    Descr  => "Flowers spring to mourn the spot from which the rabbit just hopped away."
    # hamrless. bad luck if hurt?
  },
  dragon => {
    Name   => "zodiac dragon",
    Descr  => "The dragon impatiently melts winter snow into a stillborn spring.",
    Projectile => ["+", "orange", "chain"]
    # *** src of memories or manipulates them?
  },
  ox => {
    Name   => "zodiac ox",
    Descr  => "The ox stampedes in circles by the sick room.",
    # aggressive/calm random cycles
  },
  snake => {
    Name   => "zodiac snake",
    Descr  => "The snake slithers his way into the most charming locations.",
    # charms females
  },
  tiger => {
    Name   => "zodiac tiger",
    Descr  => "The tiger sweats under the scrutinizing sun's cloudy eyes.",
    # shy
  },
  sheep => {
    Name   => "zodiac sheep",
    Descr  => "The sheep bows its head at the storm on the less green side of this field."
    # independent
  },
  monkey => {
    Name   => "zodiac monkey",
    Descr  => "The monkey is fumbling to find a worthwhile puzzle to lose sleep over.",
    # hurts self trying to communicate
  },
  horse => {
    Name   => "zodiac horse",
    Descr  => "The horse neighs uselessly, leaving her hair at the hospital.",
    # avoids males, fight to death if provoked
  },
  rooster => {
    Name   => "zodiac rooster",
    Descr  => "The rooster wastes time gazing east in a covered cage.",
    # follows ppl but doesnt attack
  },
  Anonymous => {
    Name   => "Anonymous",
    Descr  => "A tall faceless suit glides by. We are Legion. Anonymous does not forgive or
               forget.",
  },
  dromedary => {
    Name    => "mechanical dromedary",
    Descr   => "A camel is clanking along slowly. If its lifeless eyes could express
               anything, they would probably comment on the lack of sand. Its single hump
               is affixed to its torso with such a malice...!",
    Projectile => ["%", "Blue"]
  },
  turtle => {
    Name  => "turtle",
    Descr => "A massive turtle lumbers towards you. Small smokestack-like appendages spill
              from beneath its plated brass shell."
  },
  spider => {
    Name   => "mechanical spider",
    Descr  => "A mechanical spider scuttles along, clicking its rusty pincers maliciously
               while gears feverishly spin a web of lies deep in the spider's abdomen.",
    Projectile => ["=", "Purple"]
  },
  goat => {
    Name   => "demonic goat",
    Descr  => "A demonic goat walks calmly towards you... too calmly. Its eyes glint with
               pure evil -- all three of them. Its horns are twisted with sin.",
  },
  tentacle => {
    Name   => "rogue tentacle",
    Descr  => "A disembodied tentacle slimily thrashes towards the nearest female scent.
               Watch it!",
    Projectile => ["~", "Blue"]
    # stealthy
    # goes for females
  },
  zeppelin => {
    Name   => "zeppelin insectoid",
    Descr  => "A miniature zeppelin floats gently along. Take heed; its blimp-like abdomen 
               are said to contain a band of sky pirates with <red>deadly<grey>
               sarcasm...",
  },
  emoticon => {
    Name   => "emoticon",
    Descr  => "An emoticon dances past. Can your emotions really be expressed by a waggling
               tongue or tensed up face? Maybe not, but here, an emoticon could
               <white>define<grey> your emotions...",
  },
  codebug => {
    Name   => "code bug",
    Descr  => "A logical fallacy or a simple typo skitters towards you. The code bugs
               spread easily, quarantine it or allow reality to crumble with uninitialized 
               value warnings...",
    Pack   => 1
    # if one member of party attacked, all members feel it (viral)
  },
  worrywart => {
    Name   => "worry wart",
    Descr  => "A worry wart approaches, with a thorn to pierce your deepest paranoia.",
  },
  mosquito => {
    Name   => "mechanical mosquito",
    Descr  => "You begin to involuntarily itch as a mechanical mosquito buzzes somewhere
               nearby... Its proboscis is rusty with dried blood.",
    Pack   => 1
  },
  serpent => {
    Name   => "snow serpent",
    Descr  => "You barely make out a snow serpent slithering past. It's nearly
               indistinguisable from its surroundings; that could give it both a weakness
               and an advantage."
    # only certain areas
  },
  steambubble => {
    Name   => "steam bubble",
    Descr  => "A small steaming bubble lobs towards you. Watch out!"
  },
  clockbot => {
    Name   => "rogue clockwork bot",
    Descr  => "A rogue clockwork automatum waddles past, the gears in its head spinning as 
               it imagines and quantifies mechanical sheep."
    # like the ones MadSci makes
  },
  toysoldier => {
    Name   => "wind-up toy soldier",
    Descr  => "A toy soldier marches by, mouth painted in an expression of malice. It
               carries a guard's lance and has a wind-up key protruding from its back.",
    Pack   => 1
    # limited number of Attacks after being awoken
  },
  roguegear => {
    Name   => "spinning gear",
    Descr  => "A rusty gear spins through the air, detached from its mechanism."
  },
  wolf => {
    Name   => "mechanical wolf",
    Descr  => "A mechanical wolf clanks by. Its fur is woven from thousands of miniscule
               interlocking mechanisms, and it seems to carry the strength of an entire
               pack.",
    Pack   => 1
    # attack any of pack = grudge
  },
  octopus => {
    Name   => "mechanical octopus",
    Descr  => "A gargantuan mechanical octopus oozes towards you slowly. It contains
               massive resoirvoirs of ink for etching memories, and its tentacles thrash
               with a familiar enthusiasm."
  },
  memory => {
    Name   => "rogue memory",
    Descr  => "A rogue memory continuously manipulates time to overcome Zeno's Paradox and 
               approach you. It warps the space around it with a curious mixture of the
               past."
    # tmp changes your stats
  },
  eyeball => {
    Name   => "homunculus eye",
    Descr  => "A tiny homunculus eye rolls around. You have a homunculus interpreting
               \"reality\" for you as well, but this one doesn't seem so keen on helping
               you."
    # reduces FOV
  },
  joke => {
    Name   => "joke",
    Descr  => "The laughter of a friend menancingly echoes somewhere nearby.",
    _jawbreaker => {
      Msg => "She's been licking it... or is this after_eat for it?"
      # Afterwards, create and drop jawbreaker magically
    }
  },
  teddybear => {
    Name   => "teddy bear",
    Descr  => "A soft teddy bear, just larger than you, lumbers past, looking for a
               hug...",
    # TODO heh this doesnt even fit the attack pattern at all anyway ^^
    _hug => {
      After => sub {
        my ($attack, $heap, $self) = @_;
        my $victim = $attack->{targets}[0];
        if (my $w = delete $victim->{Equipment}{Weapon}) {
          delete $w->{On};
          $w->{Owner}->del($w);
          $self->{Inv}->add($w);
          if (GAME->client) {
            $self->saymsg("[subj] hugs [1], taking their [2].", $victim, $w);
            UI->{Status}->update("Weapon");
          }
        }
      }
    }
  },
  BSOD => {
    Name   => "Blue Screen of Death",
    Descr  => "A Blue Screen of Death lumbers towards you, constantly having to synchronize
               its commands with various botnets."
    # summons bugs
    # crash: self destruct and rush in
    # freeze/paralyze
  },
  snowgolem => {
    Name   => "snow golem",
    Descr  => "A massive snow golem lumbers towards you through the chilly wind. Its
               patched together with spit, prayers, and snow, but appears deadly due to its
               size and connection with its surroundings."
    # spawns in snow areas?
  },
  mandrake => {
    Name   => "mandrake",
    Descr  => "A mandrake root is burrowed in the ground nearby. Though it remains
               motionless, its hand-like tendrils curl threateningly.",
    Pack   => 1
    # doesnt move
    # spawn in clumps
  },
  clown => {
    Name  => "clown",
    Descr => "A menacing clown lumbers by, cackling at some joke over your head."
  },
  steamcloud => {
    Name   => "steam cloud",
    Descr  => "A massive steam cloud billows towards you, blanketing everything in its path
               with scalding steam. It seems fresh from a smokestack, whether nearby or
               not."
    # explode on contact, but area effect
  },
  icestatue => {
    Name   => "ice statue",
    Descr  => "An ice statue is frozen in a combat pose. You should go check it out; it
               doesn't look mobile.",
    Pack   => 1
    # can surround you
  },
  drone => {
    Name   => "factory drone",
    Descr  => "The shell of a past Cyphen citizen marches towards you, apparel greasy with 
               a factory's tell-tale rust. It wields a hacked-together congloberation of
               machinery."
    # drops certain items
  },
  kraken => {
    Name   => "air kraken",
    Descr  => "A massive kraken slices through the sky, tentacles flailing."
    # 
  },
  angel => {
    Name   => "mechanical angel",
    Descr  => "A mechanical angel descends upon you. It glows with false illumination, its 
               wings seem to be crudely stitched on, and it radiates anything but Heaven's 
               aura."
    # 
  },
  demon => {
    Name   => "mechanical demon",
    Descr  => "A mechanical demon descends upon you. Its scaly wings have been welded to
               its frame, and its reptilian tail taps out the rhythm of factory machinery."
    # 
  },
  gumbybrain => {
    Name   => "GumbyBRAIN",
    Descr  => "GumbyBRAIN, a network of fizzing neurons, floats towards you. Symbols flash 
               through the synapses. It carries a rusty chain."
    # quotes
    # markov chain
  },
  succubus => {
    Name   => "succubus",
    Descr  => "Nearby males begin involuntarily reading in the dark as a succubus
               approaches, its every movement an ecstacy of hypersensitive tactile
               sensation..."
    # permanently drain HP from males
    # take armour
    # most attractive thing imaginable, parasite. seem to fulfill dreams but only make
    # nightmares
  },
  incubus => {
    Name   => "incubus",
    Descr  => "A muscular incubus walks lightly towards the nearest female."
    # let chip describe this one
    # permanently drain HP from females
    # take armour
  },
  shadow => {
    Name   => "eyecorner's shadow",
    Descr  => "You spot a shadow out of the corner of your eye... or is it just your
               imagination?"
    # 
  },
  friendzone => {
    Name   => "friend zone",
    Descr  => "You're nothing more than a shoulder to cry on, never the problem itself. The
               Friend Zone will remind you of this."
    # scatters males/females in group
  },
  oroborous => {
    Name   => "Oroborous",
    Descr  => "An endless loop of an Oroborous comes into view. It constantly consumes
               itself, yet never attacks..."
    # swallows you, escape maze flooding with stomach acid
  },
);

my @baddies;
foreach my $entry (@table) {
  my $type = shift @$entry;
  unless ($dat{$type}) {
    return "no monster data for $type";
  }
  $dat{$type}->{Type} = $type;

  if (my $ls = $attacks{$type}) {
    foreach my $dat (@$ls) {
      my (%attack, @fx);
      (@attack{qw(Name Range Lag DBase)}, @fx) = @$dat;
      $attack{Range} = ["adj"] if $attack{Range} eq "adj";
      $dat{$type}->{Attacks}{ $attack{Name} } = Game::Attack->new(%attack, @fx);
    }
  }

  # Extra attack data
  foreach my $atk (keys %{ $dat{$type} }) {
    next unless $atk =~ s/^_//;
    my %extra = %{ delete $dat{$type}->{"_$atk"} };
    $dat{$type}->{Attacks}{$atk}{$_} = $extra{$_} foreach keys %extra;
  }

  for (0 .. $#cols) {
    my $attrib = $cols[$_];
    if ($attrib =~ m/(Symbol|Color|Speed|Rank)/) {
      $dat{$type}->{$attrib} = $entry->[$_];
    } else {
      $dat{$type}->{Stats}{$attrib} = $entry->[$_];
    }
  }
  push @baddies, delete $dat{$type};
}
if (%dat) {
  return ["monster dat not in table", keys %dat];
}

# Finally, transform this monster data into real packages
my @packages;
foreach my $enemy (@baddies) {
  my $type = delete $enemy->{Type};
  my $package = "Game::Stuff::Monster::$type";
  push @packages, $package;
  eval "package $package; use base 'Game::StdLib::Character::Monster';";
  $package->announce($type);
  $package->classdat(%$enemy);
}

@packages;
